# Core
db:
  redis:
    namespace: EG

# plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config' 

crypto:
  cipherKey: sensitiveKey
  cipherSalt: sensitiveSalt
  algorithm: aes256
  saltRounds: 10
